- name: Restart {{ compose_generator_service }}
  register: compose_generator_restart_service
  ansible.builtin.shell: # noqa command-instead-of-shell
    chdir: "{{ compose_generator_appdata_path }}/{{ compose_generator_service }}"
    cmd: "{{ compose_generator_update_command }}"
  changed_when: compose_generator_restart_service.rc != 0
