---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: controllers
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: controllers
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: v1.12.4
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: controllers
      interval: 10m
  values:
    installCRDs: true
    extraArgs:
      - --enable-certificate-owner-ref=true
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
