---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: secrets
spec:
  interval: 24h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.9.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: secrets
      interval: 10m
  values:
    installCRDs: true
    prometheus.enabled: false
