---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minicloudlabs
  namespace: controllers
spec:
  interval: 24h
  url: https://minicloudlabs.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatus
  namespace: controllers
spec:
  interval: 10m
  chart:
    spec:
      chart: gatus
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: minicloudlabs
        namespace: controllers
      interval: 10m
  values:
    image:
      repository: ghcr.io/twin/gatus
      tag: v5.5.1

    persistence:
      storageClassName: longhorn
      enabled: true

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: roxedus.com-cloudflare
      hosts:
        - status.roxedus.com
      tls:
        - secretName: status-roxedus-tls
          hosts:
            - status.roxedus.com

    config:
      storage:
        type: sqlite
        path: /data/data.db
      endpoints:
        - name: Roxedus
          url: https://roxedus.dev
          conditions:
            - "[STATUS] == 200"
