---
apiVersion: v1
kind: Namespace
metadata:
  name: intel-dp
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: intel-device-plugins-for-kubernetes
  namespace: intel-dp
spec:
  interval: 5m
  url: https://github.com/intel/intel-device-plugins-for-kubernetes
  ref:
    tag: v0.28.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-for-kubernetes-nfd
  namespace: intel-dp
spec:
  interval: 10m
  # targetNamespace: intel-dp
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
    namespace: intel-dp
  path: /deployments/nfd
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-for-kubernetes-nfd-feature-rules
  namespace: intel-dp
spec:
  interval: 10m
  # targetNamespace: intel-dp
  dependsOn:
    - name: intel-device-plugins-for-kubernetes-nfd
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
    namespace: intel-dp
  path: /deployments/nfd/overlays/node-feature-rules
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-for-kubernetes-nfd-fractional-resources
  namespace: intel-dp
spec:
  interval: 10m
  targetNamespace: intel-dp
  dependsOn:
    - name: intel-device-plugins-for-kubernetes-operator
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
    namespace: intel-dp
  path: /deployments/gpu_plugin/overlays/fractional_resources
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-for-kubernetes-operator
  namespace: intel-dp
spec:
  interval: 10m
  # targetNamespace: intel-dp
  #  dependsOn:
  #    - name: intel-device-plugins-for-kubernetes-nfd-fractional-resources
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
    namespace: intel-dp
  path: /deployments/operator/default
  prune: true
  timeout: 1m
  patches:
    - patch: |-
        kind: not-important
        metadata:
          name: not-important
        spec:
          template:
            spec:
              nodeSelector:
                kubernetes.io/arch: amd64
      target:
        kind: (StatefulSet|Deployment|Job)
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-for-kubernetes-gpu-plugin
  namespace: intel-dp
spec:
  dependsOn:
    - name: intel-device-plugins-for-kubernetes-operator
  interval: 10m
  targetNamespace: intel-dp
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
    namespace: intel-dp
  path: /deployments/gpu_plugin
  prune: true
  timeout: 1m
