---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: intel-device-plugins-for-kubernetes
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/intel/intel-device-plugins-for-kubernetes
  ref:
    tag: v0.27.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-for-kubernetes-nfd
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
    namespace: flux-system
  path: /deployments/nfd
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-for-kubernetes-nfd-gpu
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: intel-device-plugins-for-kubernetes-nfd
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
    namespace: flux-system
  path: /deployments/nfd/overlays/gpu
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-for-kubernetes-nfd-feature-rules
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: intel-device-plugins-for-kubernetes-nfd-gpu
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
    namespace: flux-system
  path: /deployments/nfd/overlays/node-feature-rules
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-for-kubernetes-nfd-fractional-resources
  namespace: flux-system
spec:
  targetNamespace: system
  interval: 10m
  dependsOn:
    - name: intel-device-plugins-for-kubernetes-nfd-feature-rules
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
    namespace: flux-system
  path: /deployments/gpu_plugin/overlays/fractional_resources
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-for-kubernetes-operator
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: intel-device-plugins-for-kubernetes-nfd-fractional-resources
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
    namespace: flux-system
  path: /deployments/operator
  prune: true
  timeout: 1m
  patches:
    - patch: |-
        kind: not-important
        metadata:
          name: not-important
        spec:
          template:
            spec:
              nodeSelector:
                kubernetes.io/arch: amd64
      target:
        kind: (StatefulSet|Deployment|Job)
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugins-for-kubernetes-gpu-plugin
  namespace: flux-system
spec:
  targetNamespace: system
  dependsOn:
    - name: intel-device-plugins-for-kubernetes-operator
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: intel-device-plugins-for-kubernetes
    namespace: flux-system
  path: /deployments/gpu_plugin
  prune: true
  timeout: 1m
