apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - external-secrets.yaml
  - intel-dp.yaml
  - longhorn.yaml
  - metallb.yaml
  - metrics-server.yaml
  - terraform-controller.yaml
  - traefik.yaml
  - vault.yaml
  - weave-gitops.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: controllers
