---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 1m0s
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  targetNamespace: longhorn
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: 1.5.0

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    #force: true
    # remediation:
    #   remediateLastFailure: true
  interval: 1m0s

  values:
    bbbb: aaaa
    service:
      ui:
        type: NodePort
        nodePort: 32305

    longhornAdmissionWebhook:
      replicas: 0
    longhornConversionWebhook:
      replicas: 0
    longhornRecoveryBackend:
      replicas: 0

    persistence:
      defaultClassReplicaCount: 2
