---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: public
spec:
  interval: 5m0s
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: public
spec:
  interval: 5m
  targetNamespace: public
  chart:
    spec:
      chart: metallb
      version: 0.13.11
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 12h
  install:
    createNamespace: true
