---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: metallb-system
  sourceRef:
    kind: GitRepository
    name: metallb
    namespace: flux-system
  path: /config/native
  prune: true
  timeout: 1m
