---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/metallb/metallb
  ref:
    tag: v0.13.9
