---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: metrics-server
  namespace: controllers
spec:
  interval: 5m
  url: https://github.com/kubernetes-sigs/metrics-server
  ref:
    tag: v0.6.3
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: controllers
spec:
  interval: 10m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: metrics-server
    namespace: flux-system
  path: /manifests/release
  prune: true
  timeout: 1m
  patches:
    - target:
        kind: Deployment
        name: metrics-server
        namespace: kube-system
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --kubelet-insecure-tls
