---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/kubernetes-sigs/node-feature-discovery
  ref:
    tag: v0.13.2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery-default
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: node-feature-discovery
    namespace: flux-system
  path: /deployment/overlays/default
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-feature-discovery-topologyupdater
  namespace: flux-system
spec:
  dependsOn:
    - name: node-feature-discovery-default
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: node-feature-discovery
    namespace: flux-system
  path: /deployment/overlays/topologyupdater
  prune: true
  timeout: 1m
