---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 24h
  url: https://weaveworks.github.io/tf-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: tf-controller
      version: v0.15.0
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
      interval: 10m
  values:
    metrics:
      enabled: false
