---
apiVersion: v1
kind: Namespace
metadata:
  name: public
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
  namespace: public
spec:
  interval: 24h
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: public
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 21.2.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: public
      interval: 10m
  values:
    experimental:
      http3:
        enabled: true
      plugins:
        enabled: false
      kubernetesGateway:
        enabled: false

    additionalArguments:
      - --api.insecure=true
      - --ping
      - --ping.entrypoint=traefik

    ports:
      traefik:
        port: 9000
        expose: true
        exposedPort: 9900
        protocol: TCP
      web:
        port: 8080
        exposedPort: 80
        expose: true
        protocol: TCP
        #redirectTo: websecure
      websecure:
        port: 4443
        exposedPort: 443
        expose: true
        protocol: TCP
        tls:
          enabled: true
      metrics:
        port: 9102
        expose: false
      udp:
        port: 6666
        protocol: UDP
        expose: true

    tlsOptions:
      default:
        sniStrict: true
        minVersion: VersionTLS12

    service:
      enabled: true
      type: LoadBalancer

    providers:
      kubernetesCRD:
        allowCrossNamespace: true
      kubernetesIngress:
        publishedService:
          enabled: true

    ingressClass:
      enabled: true
      isDefaultClass: true
