---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vault
  namespace: secrets
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: secrets
      interval: 10m
  values:
    installCRDs: true
    server.dataStorage.storageClass: longhorn
    ui:
      enabled: true
      serviceType: NodePort

    global.serverTelemetry.prometheusOperator: false
