---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-volsync
spec:
  secretStoreRef:
    name: bitwarden-notes
    kind: ClusterSecretStore
  target:
    name: ${APP}-volsync
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .RESTIC_REST }}/${APP}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        RESTIC_REST_USERNAME: "{{ .RESTIC_REST_USERNAME }}"
        RESTIC_REST_PASSWORD: "{{ .RESTIC_REST_PASSWORD }}"
  dataFrom:
    - extract:
        key: 247cfa93-2894-44bb-918b-892c044a9ef1 # restic-server
