services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest@sha256:c3372a56bc12ac3d06c60002b644c0af78bfe83fb9ccc8929c3ec5ffb848b7cf
    container_name: healthchecks
    environment:
      APPRISE_ENABLED: "True"
      DEBUG: "False"
      SITE_ROOT: https://healthchecks.{{ main_domain }}
      SITE_NAME: Rostvik Estate Healthchecks
      SUPERUSER_EMAIL: me@roxedus.dev
      SUPERUSER_PASSWORD: "{{ compose_generator_password }}"
      # REGENERATE_SETTINGS: "true"
    ports:
      - 8000:8000
    labels:
      traefik.enable: "true"
