services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest@sha256:6ca4c858f1129f739051fd80472cfe88d167eaba55f2a1546226f1707db0a1f7
    container_name: healthchecks
    environment:
      APPRISE_ENABLED: "True"
      DEBUG: "False"
      SITE_ROOT: https://healthchecks.{{ main_domain }}
      SITE_NAME: Rostvik Estate Healthchecks
      SUPERUSER_EMAIL: me@roxedus.dev
      SUPERUSER_PASSWORD: "{{ compose_generator_password }}"
      # REGENERATE_SETTINGS: "true"
    ports:
      - 8000:8000
    labels:
      traefik.enable: "true"
