services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest@sha256:f961b4401fb8e31a0116e254ef11e9f8945296ad556e384bf2522deec53005c7
    container_name: healthchecks
    environment:
      APPRISE_ENABLED: "True"
      DEBUG: "False"
      SITE_ROOT: https://healthchecks.{{ main_domain }}
      SITE_NAME: Rostvik Estate Healthchecks
      SUPERUSER_EMAIL: me@roxedus.dev
      SUPERUSER_PASSWORD: "{{ compose_generator_password }}"
      # REGENERATE_SETTINGS: "true"
    ports:
      - 8000:8000
    labels:
      traefik.enable: "true"
