services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest@sha256:2f6312cf5b390a9b00a40860d08e77309034aed0b6497fdff9abed83b9de1a25
    container_name: healthchecks
    environment:
      SITE_ROOT: https://healthchecks.{{ secret_local_domain }}
      SITE_NAME: Rostvik Estate Healthchecks
      SUPERUSER_EMAIL: me@roxedus.dev
      SUPERUSER_PASSWORD: "{{ users.0.password }}"
      REGENERATE_SETTINGS: "true"
    ports:
      - 8000:8000
    labels:
      traefik.enable: "true"
