services:
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest@sha256:7d078980b369567d383ec9c6afd7f5feb66ffa4cb38f3b908e6e4f15536370a3
    container_name: healthchecks
    environment:
      APPRISE_ENABLED: "True"
      DEBUG: "False"
      SITE_ROOT: https://healthchecks.{{ main_domain }}
      SITE_NAME: Rostvik Estate Healthchecks
      SUPERUSER_EMAIL: me@roxedus.dev
      SUPERUSER_PASSWORD: "{{ compose_generator_password }}"
      # REGENERATE_SETTINGS: "true"
    ports:
      - 8000:8000
    labels:
      traefik.enable: "true"
