services:
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng:latest@sha256:46ee228b502756a7d230298c0e805bcc6179efd9c11cd4a35e8acba3e7874873
    container_name: syslog-ng
    volumes:
      - "{{ edge_docker_appdata_path }}/{{ compose_generator_service }}/config:/config"
      - "{{ edge_docker_appdata_path }}/{{ compose_generator_service }}/log:/var/log"
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
