x-skip-globals: [environment, volumes]

services:
  traefik:
    container_name: traefik
    user: "{{ compose_generator_runas }}"
    image: traefik:v2.11.0
    read_only: "true"
    environment:
      TZ: "{{ compose_generator_timezone }}"
      CF_DNS_API_TOKEN: "{{ secret_cloudflare.apikey }}"
      TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL: "{{ secret_cloudflare.email }}"
    ports:
      - 80:8080
      - 443:8443
    networks:
      - default
      - proxy
    volumes:
      - "{{ edge_docker_appdata_path }}/{{ compose_generator_service }}/config:/etc/traefik"
  dockerproxy-traefik:
    image: tecnativa/docker-socket-proxy
    container_name: dockerproxy-traefik
    read_only: "true"
    tmpfs:
      - /run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    environment:
      - CONTAINERS=1

networks:
  default: "{{ compose_generator_globals.networks.default }}"
  proxy:
    internal: true
    labels:
      ansible.managed: "true"
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.32/29
