x-skip-globals: [environment, volumes]

services:
  traefik:
    container_name: traefik
    user: "{{ compose_generator_runas }}"
    image: traefik:2.11.2
    read_only: "true"
    environment:
      TZ: "{{ compose_generator_timezone }}"
      CF_DNS_API_TOKEN: "{{ secret_cloudflare.apikey }}"
      TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL: "{{ secret_cloudflare.email }}"
    ports:
      - 80:8080
      - 443:8443
    networks:
      default:
        aliases:
          - vdi.{{ main_domain }}
      proxy:
    volumes:
      - "{{ edge_docker_appdata_path }}/{{ compose_generator_service }}/config:/etc/traefik"

  dockerproxy-traefik:
    image: ghcr.io/linuxserver/socket-proxy:1.24.0
    container_name: dockerproxy-traefik
    read_only: "true"
    tmpfs:
      - /run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    environment:
      CONTAINERS: "1"
      LOG_LEVEL: warning

  cloudflared:
    image: cloudflare/cloudflared:2024.4.0@sha256:f2a8f348ad721b1a5f2836ca63c08d9a7629081e086a530c8b8bf05bc7fe0f01
    container_name: cloudflared
    user: "{{ compose_generator_runas }}"
    read_only: "true"
    environment:
      NO_AUTOUPDATE: "true"
    volumes:
      - "{{ edge_docker_appdata_path }}/{{ compose_generator_service }}/[service_name]:/etc/cloudflared:ro"
    command: tunnel run {{ secret_cloudflare.tunnel_id }}

networks:
  default: "{{ compose_generator_globals.networks.default }}"
  proxy:
    internal: true
    labels:
      ansible.managed: "true"
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.32/29
