x-skip-globals: [volumes]

services:
  webcord:
    image: ghcr.io/linuxserver/webcord:v4.7.1-ls56@sha256:bf19941d04b6b85f0f79442e47503a5c9b14bc62aace9011bb7d94811cbb7936
    container_name: webcord
    volumes:
      - "{{ edge_docker_appdata_path }}/{{ docker_service }}/[service_name]:/config"
    environment:
      NO_DECOR: "true"
      SUBFOLDER: /webcord/
      CUSTOM_USER: Roxedus
      PASSWORD: "{{ main_password }}"
    shm_size: 1gb
    ports:
      - 3320:3000
    labels:
      traefik.enable: "false"
      traefik.http.routers.webcord-vdi.rule: Host(`vdi.{{ main_domain }}`) && PathPrefix(`/webcord`)
  element:
    image: docker.io/roxedus/playground:element
    container_name: element
    volumes:
      - "{{ edge_docker_appdata_path }}/{{ docker_service }}/[service_name]:/config"
    environment:
      NO_DECOR: "true"
      SUBFOLDER: /element/
      CUSTOM_USER: Roxedus
      PASSWORD: "{{ main_password }}"
    shm_size: 1gb
    ports:
      - 3321:3000
    labels:
      traefik.enable: "false"
      traefik.http.routers.element-vdi.rule: Host(`vdi.{{ main_domain }}`) && PathPrefix(`/element`)
