---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rostvik-site
spec:
  secretName: rostvik-site-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: kube.${CLUSTER_DOMAIN}
  dnsNames:
    - kube.${CLUSTER_DOMAIN}
    - "*.kube.${CLUSTER_DOMAIN}"
