---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rostvik-site
spec:
  secretName: rostvik-site-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: kube.rostvik.site
  dnsNames:
    - kube.rostvik.site
    - "*.kube.rostvik.site"
