# https://github.com/markosamuli/ansible-linuxbrew/blob/master/tasks/install/with_installer.yml
- name: Temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: homebrew
  register: homebrew_tmp
  become: false

- name: Create folders
  become: true
  ansible.builtin.file:
    path: /home/linuxbrew/.linuxbrew/
    state: directory
    mode: "0755"
    owner: "{{ homebrew_user }}"
    group: "{{ homebrew_group }}"

- name: Download Homebrew install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
    dest: "{{ homebrew_tmp.path }}/install.sh"
    mode: "0700"
  become: false

- name: Install Homebrew with the installer
  ansible.builtin.command: sh -c "{{ homebrew_tmp.path }}/install.sh"
  register: homebrew_install_result
  changed_when: homebrew_install_result.rc == 0
  become: false
  environment:
    NONINTERACTIVE: "true"

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ homebrew_tmp.path }}"
    state: absent
  become: false
