- name: Check if homebrew directory exists
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew/
  register: homebrew_linuxbrew_path

- name: Install homebrew
  when: not homebrew_linuxbrew_path.stat.exists
  ansible.builtin.include_tasks: install.yml
