- name: Check if Chezmoi is installed
  become: false
  ansible.builtin.stat:
    path: /home/{{ rox_users_user.username }}/.local/bin/chezmoi
  register: rox_users_chezmoi_bin

- name: Create folders
  become: false
  register: rox_users_chezmoi_create
  ansible.builtin.file:
    path: /home/{{ rox_users_user.username }}/{{ item }}
    state: directory
    mode: "0775"
    owner: "{{ rox_users_user.username }}"
    group: "{{ rox_users_user.groupname }}"
  loop:
    - .local/bin
    - .config/chezmoi

- name: Download Chezmoi
  when: not rox_users_chezmoi_bin.stat.exists
  register: rox_users_chezmoi_download
  become: false
  ansible.builtin.get_url:
    url: https://github.com/twpayne/chezmoi/releases/latest/download/chezmoi-linux-{{ apt_arch }}
    dest: /home/{{ rox_users_user.username }}/.local/bin/chezmoi
    mode: "0755"
    owner: "{{ rox_users_user.username }}"
    group: "{{ rox_users_user.groupname }}"

- name: Create Chezmoi config
  when: rox_users_chezmoi_config
  become: false
  ansible.builtin.copy:
    mode: "0760"
    content: "{{ rox_users_chezmoi_config }}"
    dest: /home/{{ rox_users_user.username }}/.config/chezmoi/chezmoi.yml
    owner: "{{ rox_users_user.username }}"
    group: "{{ rox_users_user.groupname }}"

- name: Create Chezmoi age file
  become: false
  ansible.builtin.copy:
    mode: "0760"
    content: "{{ rox_users_chezmoi_age }}"
    dest: /home/{{ rox_users_user.username }}/.config/chezmoi/key.age
    owner: "{{ rox_users_user.username }}"
    group: "{{ rox_users_user.groupname }}"

- name: Init Chezmoi
  ansible.builtin.command: .local/bin/chezmoi init {{ rox_users_user.github }}
  register: rox_users_rox_users_init_result
  when: rox_users_chezmoi_create.changed and rox_users_chezmoi_download.changed
  changed_when: rox_users_rox_users_init_result.rc == 0
  become: false
  environment:
    NONINTERACTIVE: "true"

- name: Check if Chezmoi is initialized
  become: false
  ansible.builtin.stat:
    path: /home/{{ rox_users_user.username }}/.local/share/chezmoi/
  register: rox_users_chezmoi_init

- name: Apply Chezmoi
  ansible.builtin.command: .local/bin/chezmoi apply -v
  register: rox_users_rox_users_init_result
  when: rox_users_chezmoi_init.stat.exists
  changed_when: rox_users_rox_users_init_result.rc == 0
  become: false
  environment:
    NONINTERACTIVE: "true"
