- name: Provision new user
  when: not box_is_appliance
  ansible.builtin.include_tasks: user.yml

- name: Adapt root user
  when: box_is_appliance
  ansible.builtin.include_tasks: is_root.yml

- name: Install OhMyPosh
  when: box_omp
  ansible.builtin.include_tasks: omp.yml

- name: Install Chezmoi
  when: box_chezmoi
  ansible.builtin.include_tasks: chezmoi.yml

- name: Basic VI
  when: not box_chezmoi
  ansible.builtin.lineinfile:
    mode: 0644
    path: /home/{{ user.username }}/.vimrc
    line: set nocompatible
    create: yes
