- name: Provision new user
  when: not box_is_appliance
  ansible.builtin.include_tasks: user.yml

- name: Adapt root user
  when: box_is_appliance
  ansible.builtin.include_tasks: is_root.yml

- name: Install OhMyPosh
  when: box_omp
  ansible.builtin.include_tasks: omp.yml

- name: Install Chezmoi
  when: box_chezmoi
  ansible.builtin.include_tasks: chezmoi.yml

- name: Basic VI
  when: not box_chezmoi
  ansible.builtin.lineinfile:
    mode: 0644
    path: /home/{{ user.username }}/.vimrc
    line: set nocompatible
    create: true

- name: Configure login for tmux session
  ansible.builtin.blockinfile:
    path: /home/{{ user.username }}/.profile
    marker: "# ANSIBLE MANAGED BLOCK {mark}"
    insertbefore: "# if running bash"
    block: |
      if [[ -z $TMUX ]] && [[ -n $SSH_TTY ]] && [[ -n "$LC_tmux_session" ]] && [[ $- =~ i ]]; then
        session="${LC_tmux_session:-ssh}"
        unset LC_tmux_session

        if tmux has-session -t "$session" 2>/dev/null; then
          exec tmux attach-session -t "$session"
        else
          exec tmux new-session -s "$session"
        fi
      fi
