- name: Provision new user
  when: not rox_users_box_is_appliance
  ansible.builtin.include_tasks: user.yml

- name: Adapt root user
  when: rox_users_box_is_appliance
  ansible.builtin.include_tasks: is_root.yml

- name: Install OhMyPosh
  when: rox_users_box_omp
  ansible.builtin.include_tasks: omp.yml

- name: Install Chezmoi
  when: rox_users_box_chezmoi
  ansible.builtin.include_tasks: chezmoi.yml

- name: Basic VI
  when: not rox_users_box_chezmoi
  ansible.builtin.lineinfile:
    mode: 0644
    owner: "{{ rox_users_user.username }}"
    group: "{{ rox_users_user.groupname }}"
    path: /home/{{ rox_users_user.username }}/.vimrc
    line: set nocompatible
    create: true

- name: Basic tmux
  when: not rox_users_box_chezmoi
  ansible.builtin.copy:
    mode: 0644
    owner: "{{ rox_users_user.username }}"
    group: "{{ rox_users_user.groupname }}"
    dest: /home/{{ rox_users_user.username }}/.tmux.conf
    content: |
      # Enable mouse control (clickable windows, panes, resizable panes)
      set -g mouse on

      set-option -g set-titles on
      set-option -g set-titles-string "#{host} > #{window_name}"

      # split panes using | and -
      bind | split-window -h
      bind - split-window -v
      unbind '"'
      unbind %

      # switch panes using Alt-arrow without prefix
      bind -n M-Left select-pane -L
      bind -n M-Right select-pane -R
      bind -n M-Up select-pane -U
      bind -n M-Down select-pane -D

- name: Configure login for tmux session
  # https://github.com/JanDeDobbeleer/oh-my-posh/issues/1308#issuecomment-979091694
  ansible.builtin.blockinfile:
    path: /home/{{ rox_users_user.username }}/.profile
    marker: "# ANSIBLE MANAGED BLOCK {mark}"
    insertbefore: "# if running bash"
    block: |
      if [[ -z $TMUX ]] && [[ -n $SSH_TTY ]] && [[ -n "$LC_tmux_session" ]] && [[ $- =~ i ]]; then
        session="${LC_tmux_session:-ssh}"
        unset LC_tmux_session

        if tmux has-session -t "$session" 2>/dev/null; then
          exec tmux -u attach-session -t "$session"
        else
          exec tmux -u new-session -s "$session"
        fi
      fi
