---
# https://external-secrets.io/latest/examples/bitwarden/
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name bitwarden-test-secret
  namespace: external-secrets
spec:
  target:
    name: *name
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        test: |-
          {{ .test }}
  data:
    - secretKey: test
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: test
