---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      pihole-1: &controller
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          pihole-1: &container
            image:
              repository: registry.k8s.io/external-dns/external-dns
              tag: v0.14.2@sha256:3fcad62c4a9a8a72cb2db5ce7adeb121be66cac5f7f5ddad43684c2b20c72aa5
            env:
              - name: EXTERNAL_DNS_PIHOLE_SERVER
                value: http://10.0.0.31
            envFrom:
              - secretRef:
                  name: *app
            args:
              - --source=ingress
              - --source=service
              - --registry=noop
              #- --policy=upsert-only
              - --provider=pihole
              - --domain-filter=kube.${CLUSTER_DOMAIN}
              - --interval=1m
              - --log-format=text
              - --log-level=info
              - --metrics-address=:7979
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 7979
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
      pihole-2:
        <<: *controller
        containers:
          pihole-2:
            <<: *container
            env:
              - name: EXTERNAL_DNS_PIHOLE_SERVER
                value: http://10.0.0.32
    serviceAccount:
      create: true
      name: *app
    service:
      pihole-1: &service
        controller: pihole-1
        ports:
          http:
            port: *port
      pihole-2:
        <<: *service
        controller: pihole-2
    serviceMonitor:
      pihole-1: &serviceMonitor
        serviceName: external-dns-pihole-pihole-1
        enabled: true
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
      pihole-2:
        <<: *serviceMonitor
        serviceName: external-dns-pihole-pihole-2
