---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
spec:
  target:
    name: actions-runner-controller-auth-secret
    template:
      engineVersion: v2
      data:
        ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID }}
        ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID }}
        ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY }}
        ACTION_RUNNER_CONTROLLER_GITHUB_WEBHOOK_SECRET_TOKEN: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_WEBHOOK_SECRET_TOKEN }}
  dataFrom:
    - extract:
        key: 376f41c6-752b-4849-a5fc-3057844bfeca
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
