# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

exclude: ansible/\..*

repos:
  - repo: local
    hooks:
      - id: ansible-vault-encrypted
        name: Ensure vault is encrypted
        language: script
        entry: .pre-commit/ansible-vault-encrypted.sh
      - name: Ansible lint
        language: script
        id: ansible-lint
        files: ansible/
        entry: .pre-commit/ansible-lint.sh
        args:
          - -p
          - --nocolor
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
