# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

exclude: ansible/\..*

repos:
  - repo: local
    hooks:
      - id: ansible-vault-encrypted
        name: Ensure vault is encrypted
        language: script
        entry: .pre-commit/ansible-vault-encrypted.sh

      - id: ansible-lint
        files: ^ansible/
        name: Ansible-lint
        description: This hook runs ansible-lint.
        pass_filenames: false
        language: script
        entry: .pre-commit/ansible-lint.sh

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        types: [file, yaml]
