# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

exclude: ansible/\..*

repos:
  - repo: local
    hooks:
      - id: ansible-vault-encrypted
        name: Ensure vault is encrypted
        language: script
        entry: .pre-commit/ansible-vault-encrypted.sh
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.31.0
    hooks:
      - id: yamllint
        types: [file, yaml]
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.15.0
    hooks:
      - id: ansible-lint
        args:
          - --nocolor
          - -p
          - --project-dir ansible
