---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app ferdium
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      ferdium:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: ferdium-secret
        containers:
          app:
            image:
              repository: ghcr.io/ferdium/ferdium-server
              tag: 2.0.6@sha256:f617d1008b6182188b9ae9caed7969ffa0dd84332423870d03ae5b6e8623c6cd
            env:
              APP_UR: https://ferdium.kube.rostvik.site
              CONNECT_WITH_FRANZ: false
              DATA_DIR: /data
              DB_CONNECTION: pg
              DB_PORT: 5432
              DB_SSL: false
              IS_CREATION_ENABLED: true
              IS_DASHBOARD_ENABLED: true
              IS_REGISTRATION_ENABLED: true
              JWT_USE_PEM: true
              MAIL_CONNECTION: smtp
              MAIL_SENDER: ferdium@rostvik.site
              MAIL_SSL: false
              NODE_ENV: production
              SMTP_HOST: maddy.network.svc.cluster.local
              SMTP_PORT: 2525
            envFrom: *envFrom
            resources:
              requests:
                cpu: 5m
                memory: 100Mi
              limits:
                memory: 500Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3333
    ingress:
      app:
        className: internal
        hosts:
          - host: ferdium.kube.rostvik.site
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 5Gi
        advancedMounts:
          ferdium:
            app:
              - subPath: data
                path: /data
              - subPath: recipes
                path: /app/recipes
