# ---
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# namespace: metallb-system
# resources:
#   - flux.yaml
#   - pool.yaml

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: metallb-system
spec:
  interval: 10m0s
  path: ./kubernetes/flux/roxedus.net/metallb-system/kustomization.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
