---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./ferdium/ks.yaml
  - ./redlib/ks.yaml
  # - ./satisfactory/ks.yaml
  - ./atm10/ks.yaml
  - ./searxng/ks.yaml
