---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nginx-certificates
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.flux-system.io/name: *app
  dependsOn:
    - name: cert-manager-issuers
  path: ./flux-system/apps/network/nginx/certificates
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app nginx-external
#   namespace: flux-system
# spec:
#   targetNamespace: network
#   commonMetadata:
#     labels:
#       app.flux-system.io/name: *app
#   dependsOn:
#     - name: external-secrets-stores
#     - name: nginx-certificates
#   path: ./flux-system/apps/network/nginx/external
#   prune: false
#   sourceRef:
#     kind: GitRepository
#     name: home-flux-system
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app nginx-internal
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.flux-system.io/name: *app
  dependsOn:
    - name: nginx-certificates
  path: ./flux-system/apps/network/nginx/internal
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
