---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app bitwarden
  namespace: external-secrets
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      bitwarden:
        containers:
          app:
            command:
              - sleep
              - infinity
            image:
              repository: ghcr.io/roxedus/bw
              tag: 2024.2.1@sha256:842ac46da4c5cf9824b386418663605f27880924a2f5968027ba3ed9586ef122
            envFrom:
              - secretRef:
                  name: bitwarden-secret
            probes:
              liveness:
                enabled: false
                custom: true
                spec:
                  periodSeconds: 120
                  exec:
                    command:
                      - sh,
                      - -c,
                      - curl -X POST -s http://127.0.0.1:8087/sync | jq -e '.success == true'
                  timeoutSeconds: 5
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 512Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8087
