---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ferdium
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/default/ferdium/app
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: external-secrets-stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ferdium-volsync
  namespace: flux-system
spec:
  targetNamespace: default
  path: ./kubernetes/kustomize/volsync
  dependsOn:
    - name: ferdium
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      APP: ferdium
      VOLSYNC_CACHE_CAPACITY: 5Gi
      VOLSYNC_UID: &kubeguy "769"
      VOLSYNC_GID: *kubeguy
      CLAIM: ferdium-data
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
