---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ferdium
spec:
  target:
    name: ferdium-secret
    template:
      engineVersion: v2
      data:
        DB_DATABASE: &dbName ferdium
        DB_HOST: &dbHost postgres-rw.database.svc.cluster.local
        DB_USER: &dbUser "{{ .DB_USER }}"
        DB_PASSWORD: &dbPass "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: 250d5e3a-c160-4fb8-9ce5-921259ee6b05 # ferdium
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: &PGkeyRef 2ab16ec4-5e9a-4d4a-a631-d7cda45ac903
        property: password
      sourceRef: &CNPGSource
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: POSTGRES_SUPER_USER
      sourceRef: *CNPGSource
      remoteRef:
        key: *PGkeyRef
        property: username
