---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ferdium
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    controllers:
      ferdium:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: ferdium-secret
        containers:
          app:
            image:
              repository: ghcr.io/ferdium/ferdium-server
              tag: 2.0.10@sha256:c517bb24cccf0913a7878a94d64f94e7ab787be7f500a74f968c26dd768fc5bb
            env:
              APP_UR: https://ferdium.kube.${CLUSTER_DOMAIN}
              CONNECT_WITH_FRANZ: false
              DATA_DIR: /data
              DB_CONNECTION: pg
              DB_PORT: 5432
              DB_SSL: false
              IS_CREATION_ENABLED: true
              IS_DASHBOARD_ENABLED: true
              IS_REGISTRATION_ENABLED: true
              JWT_USE_PEM: true
              MAIL_CONNECTION: smtp
              MAIL_SENDER: ferdium@${CLUSTER_DOMAIN}
              MAIL_SSL: false
              NODE_ENV: production
              SMTP_HOST: maddy.network.svc.cluster.local
              SMTP_PORT: 2525
            envFrom: *envFrom
            resources:
              requests:
                cpu: 5m
                memory: 100Mi
              limits:
                memory: 500Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3333
    ingress:
      app:
        className: internal
        hosts:
          - host: ferdium.kube.${CLUSTER_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 5Gi
        advancedMounts:
          ferdium:
            app:
              - subPath: data
                path: /data
              # - subPath: recipes
              #   path: /app/recipes
