---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: 1.4.2

  interval: 1m0s

  values:
    service:
      ui:
        type: NodePort
        nodePort: 32304

    persistence:
      defaultClassReplicaCount: 2
