---
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList: 172.16.0.0/12
k8sServiceHost: 10.0.2.5
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
k8sClientRateLimit:
  qps: 28
  burst: 32
# devices: { enp+, eth+ }
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: false
    rollOutPods: true
    service:
      type: LoadBalancer
externalIPs.enabled: true
loadBalancer.algorithm: maglev
# routingMode: native
# ipv4NativeRoutingCIDR: 10.0.2.0/16
