---
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: 172.16.0.0/12
k8sServiceHost: 10.0.2.5
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
k8sClientRateLimit:
  qps: 28
  burst: 32
devices: {enp+, eth+}
hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true
    service:
      type: LoadBalancer
