---
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList: 172.16.0.0/12
k8sServiceHost: 10.0.2.5
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
k8sClientRateLimit:
  qps: 28
  burst: 32
# devices: { enp+, eth+ }
hubble:
  enabled: true
  relay:
    enabled: true
    prometheus:
      serviceMonitor:
        enabled: true
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: true
      className: internal
      hosts:
        - &host hubble.kube.rostvik.site
      tls:
        - hosts:
            - *host
  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    serviceMonitor:
      enabled: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium

operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  dashboards:
    enabled: true
    annotations:
      grafana_folder: Cilium
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
dashboards:
  enabled: true
  annotations:
    grafana_folder: Cilium
externalIPs.enabled: true
loadBalancer.algorithm: maglev
# routingMode: native
# ipv4NativeRoutingCIDR: 10.0.2.0/16
