---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  target:
    name: grafana-secret
    template:
      engineVersion: v2
      data:
        GF_DATABASE_NAME: &dbName grafana
        GF_DATABASE_HOST: postgres-rw.database.svc.cluster.local:5432
        GF_DATABASE_USER: &dbUser "{{ .GRAFANA_POSTGRES_USER }}"
        GF_DATABASE_PASSWORD: &dbPass "{{ .GRAFANA_POSTGRES_PASS }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: d5e34f56-3cd9-4c70-a85d-ab7de6d576a1 # grafana
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: &PGkeyRef 2ab16ec4-5e9a-4d4a-a631-d7cda45ac903
        property: password
      sourceRef: &CNPGSource
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
    - secretKey: POSTGRES_SUPER_USER
      sourceRef: *CNPGSource
      remoteRef:
        key: *PGkeyRef
        property: username
