docker_install_compose: true

docker_users_obj: "{{ users|selectattr('docker', 'defined') }}"
docker_users: "{{ docker_users_obj|map(attribute='username') }}"

docker_apt_arch: "{{ apt_arch }}"

docker_daemon_options:
  log-driver: journald
  log-opts:
    mode: non-blocking
