kubernetes_release: 1.27
kubernetes_apt: "{{ kubernetes_release }}.4-00"

containerd_config_default_write: true
containerd_config_cgroup_driver_systemd: true

kubernetes_management_user: "{{ users.0.username }}"
kubernetes_systemd_resolved_ini:
  - part: DNS
    value: 10.0.0.31
  - part: FallbackDNS
    value: 10.0.0.32
  - part: Domains
    value: "{{ main_domain }}"

raspberry_is_vlaned: True
