kubernetes_release: 1.32
kubernetes_apt: "{{ kubernetes_release }}.1-1.1"

containerd_config_default_write: false
containerd_config_cgroup_driver_systemd: true

kubernetes_management_user: "{{ users.0.username }}"
kubernetes_systemd_resolved_ini:
  - part: DNS
    value: 10.0.0.31
  - part: FallbackDNS
    value: 10.0.0.32
# - part: Domains
#   value: kube.{{ main_domain }} {{ main_domain }}

prom_node_exporter: False

raspberry_is_vlaned: True

netplan_gateway4: 10.0.2.1
netplan_search: []
netplan_4_dhcp: false
netplan_6_dhcp: false
netplan_vlan: 2
