ansible_become: false

ntp_package: chrony
ntp_daemon: chronyd

security_sudoers_passwordless: []
security_sudoers_passworded: []
security_ssh_permit_root_login: "yes"

package_list:
  - bash-completion
  - ca-certificates
  - curl
  - git
  - gnupg2
  - htop
  - jq
  - ncdu
  - net-tools
  - python3
  - python3-apt
  - python3-pip
  - tmux
  - vim
  - wget
