box_chezmoi: True
box_omp: False

homebrew: True

chezmoi_config: |

  data:
    integration:
      hishtory:
        enabled: true
        offline: false

      bitwarden:
        enabled: false
        managed: false

      oh_my_posh:
        enabled: true
        managed: true

      zsh:
        enabled: true
        antidote: true
        omz: false

  encryption: age
  age:
      identity: ~/.config/chezmoi/key.age
      recipient: age1gnpns0tj0yajhw5pjtl7jsxfyt0eqxcmedjf06wf8h30w75n8uys5p6czp

package_list:
  - bash-completion
  - ca-certificates
  - curl
  - git
  - gnupg2
  - htop
  - intel-gpu-tools
  - intel-media-va-driver-non-free
  - ncdu
  - neofetch
  - net-tools
  - python3
  - python3-apt
  - python3-pip
  - software-properties-common
  - tmux
  - vainfo
  - wget
  - zsh
  - lm-sensors

security_fail2ban_enabled: false

users:
  - username: roxedus
    groupname: roxedus
    home: yes
    uid: "1000"
    gid: "1000"
    docker: True
    passwordless: False
    shell: /usr/bin/zsh
    dotfiles: True
    github: Roxedus
    password: "{{ secret_sudo }}"
    zfs: True

zfs_ver: 2.1.5-1ubuntu6~22.04.2
zfs_users: "{{ users|selectattr('zfs', 'true')|map(attribute='username') }}"
