- name: Include Debian unfree
  when:
    - ansible_facts.distribution == 'Debian'
    - ansible_facts.board_name is match("ZimaBoard") or boards_intel_driver_detection_found | length>0
  ansible.builtin.include_tasks: debian-unfree.yml

- name: Install Intel drivers
  when:
    - boards_intel_driver_detection_found | length>0
  become: true
  ansible.builtin.apt:
    name:
      - "{{ boards_intel_drivers }}"
      - intel-gpu-tools
      - vainfo
    state: present

- name: Install ZimaBoard Firmwares
  when:
    - ansible_facts.distribution == 'Debian'
    - ansible_facts.board_name is match("ZimaBoard")
  become: true
  ansible.builtin.apt:
    name:
      - firmware-realtek
    state: present
