---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redlib
spec:
  target:
    name: redlib-secret
    template:
      engineVersion: v2
      data:
        REDLIB_DEFAULT_SUBSCRIPTIONS: "{{ .REDLIB_DEFAULT_SUBSCRIPTIONS }}"
  dataFrom:
    - extract:
        key: 0316aee9-fc4a-49a9-af64-08df43cda868
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
