---
apiVersion: v1
kind: Namespace
metadata:
  name: quicksync
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: quicksync
  namespace: quicksync
resources:
  - ersatztv.yaml
