- name: Get dependencies for pihole_updatelist
  become: true
  ansible.builtin.apt:
    name:
      - php-cgi
      - php-cli
      - php-curl
      - php-intl
      - php-sqlite3
      - php-xml
    state: present

- name: Checkout pihole_updatelist
  when: not pihole_updatelist_clone.stat.exists
  register: pihole_updatelist_git
  become: true
  ansible.builtin.git: # noqa: latest
    repo: https://github.com/jacklul/pihole-updatelists.git
    clone: true
    dest: /opt/pihole_updatelist
    depth: 1
    umask: "022"
  notify:
    - Make pihole_updatelist executeable
    - Install pihole_updatelist
