- name: Checkout pihole_updatelist
  when: not pihole_updatelist_clone.stat.exists
  register: pihole_updatelist
  become: True
  ansible.builtin.git: # noqa: latest
    repo: https://github.com/jacklul/pihole-updatelists.git
    clone: yes
    dest: /opt/pihole_updatelist
    depth: 1
    umask: "022"
  notify:
    - Make pihole_updatelist executeable
    - Install pihole_updatelist
