- name: Check if Nerdctl is installed
  ansible.builtin.stat:
    path: /usr/local/bin/nerdctl
  register: kubernetes_nerd_bin

- name: Check Nerdctl version
  when: kubernetes_nerd_bin.stat.exists
  ansible.builtin.command: /usr/local/bin/nerdctl --version
  changed_when: false
  register: kubernetes_nerd_ver

- name: Get latest release of Nerdctl
  delegate_to: 127.0.0.1 # Run on the control node to avoid installing the GitHub module on the target
  community.general.github_release:
    user: containerd
    repo: nerdctl
    action: latest_release
  register: kubernetes_nerd_rel

- name: Download Nerdctl
  when: not kubernetes_nerd_bin.stat.exists or kubernetes_nerd_rel.tag != ( "v" + (kubernetes_nerd_ver.stdout | replace("nerdctl version ", "")))
  become: true
  ansible.builtin.unarchive:
    src: |
      https://github.com/containerd/nerdctl/releases/download/
      {{ kubernetes_nerd_rel.tag }}/nerdctl-{{ kubernetes_nerd_rel.tag | replace("v", "") }}-linux-{{ apt_arch }}.tar.gz
    dest: /usr/local/bin
    include: nerdctl
    remote_src: true
    mode: "0755"

- name: Download Cilium-cli
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-{{ apt_arch }}.tar.gz
    dest: /usr/local/bin
    include: cilium
    remote_src: true
    mode: "0755"

- name: Download Hubble-cli
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/cilium/hubble/releases/latest/download/hubble-linux-{{ apt_arch }}.tar.gz
    dest: /usr/local/bin
    include: hubble
    remote_src: true
    mode: "0755"

- name: Add kubectl alias to bash
  when: is_controlplane is defined
  ansible.builtin.lineinfile:
    mode: "0644"
    path: /home/{{ kubernetes_management_user }}/.bashrc
    line: "{{ item }}"
    create: true
  with_items:
    - source <(kubectl completion bash)
    - alias k=kubectl
    - complete -F __start_kubectl k
