- name: Add kubectl alias to bash
  ansible.builtin.lineinfile:
    mode: 0644
    path: /home/{{ users.0.username }}/.bashrc
    line: "{{ item }}"
    create: yes
  with_items:
    - source <(kubectl completion bash)
    - alias k=kubectl
    - complete -F __start_kubectl k
