- name: Add repo for non-free firmware
  when: ansible_distribution == 'Debian'
  become: True
  ansible.builtin.apt_repository:
    filename: debian-non-free
    repo: "{{ item  }}"
    mode: 0666
    update_cache: True
  loop:
    - deb http://deb.debian.org/debian/ {{ ansible_facts.distribution_release }} non-free
    - deb-src http://deb.debian.org/debian/ {{ ansible_facts.distribution_release }} non-free

- name: Install firmwares
  when: ansible_distribution == 'Debian'
  become: True
  ansible.builtin.apt:
    name:
      - firmware-realtek
      - i965-va-driver-shaders
      - intel-gpu-tools
      - vainfo
    state: present

- name: Install firmwares
  when: ansible_distribution == 'Ubuntu'
  become: True
  ansible.builtin.apt:
    name:
      - i965-va-driver-shaders
      - intel-gpu-tools
      - vainfo
    state: present
