- name: Add yq repository from PPA
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:rmescandon/yq
    codename: "{{ 'jammy' if ansible_distribution == 'Debian' else '' }}"

- name: Update apt cache
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  become: true
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install Netplan
  become: true
  when: ansible_distribution == 'Debian'
  ansible.builtin.apt:
    name:
      - netplan.io
    state: present

- name: Install YQ and tmux
  become: true
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  ansible.builtin.apt:
    name:
      - yq
      - tmux
    state: present

- name: Deny dhcp by dhcpcd
  become: true
  when: not netplan_4_dhcp
  ansible.builtin.lineinfile:
    path: /etc/dhcpcd.conf
    regexp: ^denyinterfaces {{ netplan_interface }}
    line: denyinterfaces {{ netplan_interface }}
    owner: root
    group: root
    create: yes
    mode: 0644

- name: Look for Netplan conversion
  become: true
  when: ansible_distribution == 'Debian'
  ansible.builtin.stat:
    path: /etc/network/interfaces.netplan-converted
  register: _netplan_dir

- name: Run Netplan migration
  when:
    - ansible_distribution == 'Debian'
    - not _netplan_dir.stat.exists
  become: true
  ansible.builtin.command:
    environment:
      ENABLE_TEST_COMMANDS: "1"
    argv:
      - netplan
      - migrate
    creates: /etc/netplan/10-ifupdown.yaml

- name: Uninstall ifupdown
  when:
    - ansible_distribution == 'Debian'
    - not _netplan_dir.stat.exists
  become: true
  ansible.builtin.apt:
    name:
      - ifupdown
    state: absent

- name: Capturing Existing Configurations
  ansible.builtin.find:
    paths: /etc/netplan
    patterns: "*.yml,*.yaml"
  register: _netplan_configs

- name: List Existing Configurations
  ansible.builtin.debug:
    var: _netplan_configs
  when: debug is defined and ( debug | bool )

- name: Removing Existing Configurations
  ansible.builtin.file:
    path: "{{ item['path'] }}"
    state: absent
  become: true
  with_items: "{{ _netplan_configs['files'] }}"
  when:
    - item['path'] != netplan_config_file

- name: Generate 00-ansible.yaml Netplan file
  ansible.builtin.template:
    src: 00-ansible.yaml.j2
    dest: "{{ netplan_config_file }}"
    mode: 0600
    owner: root
    group: root
    validate: yq e '.' %s
  notify:
    - Try Netplan
  become: true
