- name: Create {{ docker_service }} directory # noqa name[template]
  ansible.builtin.file:
    path: "{{ docker_appdata_path }}/{{ docker_service }}"
    state: directory
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Read {{ docker_service }} compose definition # noqa name[template]
  ansible.builtin.include_vars:
    file: files/{{ docker_service }}.yml
    name: compose

- name: Install {{ docker_service }} compose file # noqa name[template]
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ docker_appdata_path }}/{{ docker_service }}/compose.yaml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"
    validate: docker compose -f %s config
  notify:
    - Restart {{ docker_service }}
  become: true
