- name: Create {{ compose_generator_service }} directory # noqa name[template]
  ansible.builtin.file:
    path: "{{ compose_generator_appdata_path }}/{{ compose_generator_service }}"
    state: directory
    owner: "{{ compose_generator_user }}"
    group: "{{ compose_generator_group }}"
    mode: "{{ compose_generator_compose_directory_mask }}"
  become: true

- name: Read {{ compose_generator_service }} compose definition # noqa name[template]
  ansible.builtin.include_vars:
    file: files/{{ compose_generator_service }}.yml
    name: compose_generator_compose

- name: Install {{ compose_generator_service }} compose file # noqa name[template]
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ compose_generator_appdata_path }}/{{ compose_generator_service }}/compose.yaml"
    mode: "{{ compose_generator_compose_file_mask }}"
    owner: "{{ compose_generator_user }}"
    group: "{{ compose_generator_group }}"
    validate: docker compose -f %s config
  notify:
    - Restart {{ compose_generator_service }}
  become: true
