- name: Set pihole webpassword
  become: True
  ansible.builtin.lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: ^WEBPASSWORD=
    line: WEBPASSWORD={{ pihole.password | hash("sha256") | hash("sha256") | default("") }}

- name: Set pihole theme
  become: True
  ansible.builtin.lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: ^WEBTHEME=
    line: WEBTHEME=default-dark # default-dark default-darker default-light

- name: Set pihole layout
  become: True
  ansible.builtin.lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: ^WEBUIBOXEDLAYOUT=
    line: WEBUIBOXEDLAYOUT=boxed

- name: Set pihole listen
  become: True
  ansible.builtin.lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: ^DNSMASQ_LISTENING=
    line: DNSMASQ_LISTENING=bind

- name: Set pihole fqdn forwarding
  become: True
  ansible.builtin.lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: ^DNS_FQDN_REQUIRED=
    line: DNS_FQDN_REQUIRED=true

- name: Set pihole reverse lookup
  become: True
  ansible.builtin.lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: ^DNS_BOGUS_PRIV=
    line: DNS_BOGUS_PRIV=true

- name: Set pihole iCloud relay
  become: True
  ansible.builtin.lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: ^BLOCK_ICLOUD_PR=
    line: BLOCK_ICLOUD_PR=false

- name: Set pihole upstream1 ipv4
  become: True
  ansible.builtin.lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: ^PIHOLE_DNS_1=
    line: PIHOLE_DNS_1=127.0.0.1#5335

- name: Set pihole upstream2 ipv4
  become: True
  ansible.builtin.lineinfile:
    path: /etc/pihole/setupVars.conf
    regexp: ^PIHOLE_DNS_2=
    line: PIHOLE_DNS_2=127.0.0.1#5335
