# - name: Set pihole webpassword
#   become: true
#   community.general.ini_file:
#     path: /etc/pihole/setupVars.conf
#     regexp: ^WEBPASSWORD=
#     line: WEBPASSWORD={{ pihole.password | hash("sha256") | hash("sha256") | default("") }}

- name: Set pihole settings
  register: pihole_settings_updated
  changed_when: pihole_settings_updated.rc != 0
  become: true
  ansible.builtin.command:
    cmd: pihole-FTL --config {{ item.key }} {{ item.value }}
  with_dict:
    dns.domainNeeded: "true"
    dns.expandHosts: "true"
    dns.specialDomains.iCloudPrivateRelay: "false"
    dns.upstreams: '[\"127.0.0.1#5335\"]' # yamllint disable rule:quoted-strings
    dns.listeningMode: BIND
    webserver.interface.boxed: "true"
    webserver.interface.theme: default-dark
    misc.etc_dnsmasq_d: "true"
