- name: Check if PiHole is cloned
  ansible.builtin.stat:
    path: /etc/pihole
  register: pihole_clone

- name: Gather PiHole
  when: not pihole_clone.stat.exists
  ansible.builtin.include_tasks: gather.yml

- name: Check if PiHole is installed
  ansible.builtin.stat:
    path: /usr/local/bin/pihole
  register: pihole_bin

- name: Configure PiHole
  when: pihole_bin.stat.exists
  ansible.builtin.include_tasks: configure.yml

- name: Place MoTD
  become: true
  when: pihole_bin.stat.exists
  ansible.builtin.copy:
    src: motd.sh
    mode: 0755
    dest: /etc/update-motd.d/02-pihole

- name: Update PiHole
  when: pihole_bin.stat.exists and pihole_update
  ansible.builtin.include_tasks: update.yml
