---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: default
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-configs
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: flux-system
  path: kubernetes/apps/
  prune: true
  wait: true
  timeout: 5m0s
