---
apiVersion: v1
kind: Namespace
metadata:
  name: tigera-operator
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: projectcalico
  namespace: tigera-operator
spec:
  interval: 24h
  url: https://docs.tigera.io/calico/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calico
  namespace: tigera-operator
spec:
  interval: 24h
  chart:
    spec:
      chart: tigera-operator
      version: v3.26.1
      sourceRef:
        kind: HelmRepository
        name: projectcalico
        namespace: tigera-operator
      interval: 10m
  values:
    phoney: true
    installation:
      cni:
        type: Calico
      calicoNetwork:
        bgp: Disabled
        ipPools:
          - cidr: 10.32.0.0/12
            encapsulation: VXLANCrossSubnet
