- name: Check if ZFS is installed
  ansible.builtin.stat:
    path: /usr/sbin/zfs
  register: zfs_bin

- name: Install ZFS
  when: not zfs_bin.stat.exists
  ansible.builtin.include_tasks: install.yml

- name: Give user passwordless access to ZFS commands
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/zfs
    line: "{{ item }} ALL=(ALL) NOPASSWD: /usr/sbin/zfs,/usr/sbin/zpool"
    regexp: ^{{ item }} .*/usr/sbin/zfs,/usr/sbin/zpool$
    validate: visudo -cf %s
    mode: 0440
  loop: "{{ zfs_users }}"
