- name: Kube | systemctl restart systemd-modules-load.service
  become: True
  ansible.builtin.service:
    name: systemd-modules-load.service
    state: restarted
  changed_when: false
  failed_when: false

- name: Kube | docker options changed
  become: True
  ansible.builtin.service:
    name: docker.service
    state: restarted
  changed_when: false
  failed_when: false

- name: Kube | sysctl --system
  become: True
  ansible.builtin.command: sysctl --system
  changed_when: false
  failed_when: false

- name: Kube | boot options changed
  become: True
  changed_when: false
  failed_when: false
  ansible.builtin.reboot:
    msg: Reboot initiated by Ansible boot options changes
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime

- name: Kube | systemd-resolved installed
  become: True
  register: systemd_resolved
  community.general.ini_file:
    mode: 0644
    path: /etc/systemd/resolved.conf
    section: Resolve
    option: "{{item.part}}"
    value: "{{item.value}}"
    no_extra_spaces: true
  with_items: "{{ kubernetes_systemd_resolved_ini }}"
  notify:
    - Kube | systemd-resolved changed

- name: Kube | systemd-resolved changed
  become: True
  ansible.builtin.service:
    name: systemd-resolved
    state: started
    enabled: True
