---
originRequest:
  originServerName: pub.${CLUSTER_DOMAIN}

ingress:
  - hostname: ${CLUSTER_DOMAIN}
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - hostname: "*.${CLUSTER_DOMAIN}"
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - service: http_status:404
