---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app satisfactory
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        name: bjw-s
        kind: HelmRepository
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      satisfactory:
        type: statefulset
        replicas: 0
        containers:
          app:
            image:
              repository: ghcr.io/wolveix/satisfactory-server
              tag: v1.9.9@sha256:9291f3d319c458511e3eee538428ff47ac6bd33e50b742450e5bf78427bd85de
            env:
              ROOTLESS: true
              # AUTOPAUSE: false
              # AUTOSAVENUM: 15
              MAXTICKRATE: 120 # default is 30
              # SKIPUPDATE: true
            resources:
              requests:
                memory: 4Gi
              limits:
                memory: 8Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      app:
        controller: *app
        enabled: true
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.0.2.46
        ports:
          game-udp:
            enabled: true
            port: 7777
            protocol: UDP
          game-tcp:
            enabled: true
            port: 7777
            protocol: TCP
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 6
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      data:
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 25Gi
        advancedMounts:
          satisfactory:
            app:
              - path: /config
      gamefiles:
        accessMode: ReadWriteOnce
        storageClass: longhorn
        size: 10Gi
        advancedMounts:
          satisfactory:
            app:
              - path: /config/gamefiles
