---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: alertmanager-secret
    template:
      engineVersion: v2
      data:
        alertmanager.yaml: |
          global:
            resolve_timeout: 5m
          route:
            group_by:
              - alertname
              - job
            group_interval: 10m
            group_wait: 1m
            receiver: pushover
            repeat_interval: 12h
            routes:
              - receiver: heartbeat
                group_interval: 5m
                group_wait: 0s
                matchers:
                  - alertname =~ "Watchdog"
                repeat_interval: 5m
              - receiver: "null"
                matchers:
                  - alertname =~ "InfoInhibitor"
              - receiver: pushover
                continue: true
                matchers:
                  - severity = "critical"
          inhibit_rules:
            - equal:
                - alertname
                - namespace
              source_matchers:
                - severity = "critical"
              target_matchers:
                - severity = "warning"
            - name: "null"
            - name: discord
              discord_config:
                - webhook_url: "{{ .DISCORD_WEBHOOK_URL }}"

  dataFrom:
    - extract:
        key: 6a1254f9-6327-4214-b7c4-4bb750898b31 # alertmanager
