apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: roxedus.com-cloudflare
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: CLOUDFLARE_API_KEY
