---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
  namespace: external-secrets
spec:
  provider:
    vault:
      server: http://vault.secrets:8200
      path: secret
      version: v2
      auth:
        jwt:
          path: jwt
          role: my-role
          kubernetesServiceAccountToken:
            serviceAccountRef:
              name: default
            audiences:
              - https://kubernetes.default.svc.cluster.local
            expirationSeconds: 600
