---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# https://external-secrets.io/latest/examples/bitwarden/
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name bitwarden-test-secret
  namespace: external-secrets
spec:
  target:
    name: *name
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        test: |-
          {{ .test }}
        json: |-
          {{ (.json | fromJson).yeet.foo}}
        yaml: |-
          {{ (.yaml | fromYaml).some.aaa}}
        yeet: |-
          {{ .yeet }}
  data:
    - secretKey: test
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: &TestRef e3448a34-f082-4e93-8988-a779eb1afc84 # test
    - secretKey: json
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: *TestRef
        property: json
    - secretKey: yaml
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: d114c439-fc5f-43e5-9431-22404470cdff # yamltest
  dataFrom:
    - extract:
        key: 2e973124-5256-4c90-b203-b24c2b8bb822 # jsontest
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
