path: .
exclude-paths:
  - kubernetes/flux/flux-system/gotk-components.yaml
  - kubernetes
# secrets-regexes-path: .kics/rules.json
# include-queries:
#   - a88baa34-e2ad-44ea-ad6f-8cac87bc7c71
output-path: .kics/
