- name: Install packages
  become: true
  when: item is string
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - libraspberrypi-bin
    - "{{ 'linux-modules-extra-raspi' if raspberry_is_vlaned else false }}"
    - "{{ 'vlan' if raspberry_is_vlaned else false }}"

- name: Add the 802.1q module
  become: true
  when: raspberry_is_vlaned
  community.general.modprobe:
    name: 8021q
    state: present

- name: Place PoE fan file
  become: true
  ansible.builtin.copy:
    content: |
      # Ansible managed

      dtoverlay=rpi-poe
      dtparam=poe_fan_temp0=57000
      dtparam=poe_fan_temp1=60000
      dtparam=poe_fan_temp2=63000
      dtparam=poe_fan_temp3=66000

      dtoverlay=vc4-fkms-v3d
    mode: 0644
    dest: /boot/firmware/usercfg.txt

- name: Deny dhcp by dhcpcd
  become: true
  when: raspberry_is_vlaned
  ansible.builtin.lineinfile:
    path: /etc/dhcpcd.conf
    regexp: ^denyinterfaces eth0
    line: denyinterfaces eth0
    owner: root
    group: root
    mode: 0644
