---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dragonfly-operator
rules:
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [""] # yamllint disable-line rule:quoted-strings
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [""] # yamllint disable-line rule:quoted-strings
    resources: [pods, services]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [apps]
    resources: [statefulsets]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [dragonflydb.io]
    resources: [dragonflies]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [dragonflydb.io]
    resources: [dragonflies/finalizers]
    verbs: [update]
  - apiGroups: [dragonflydb.io]
    resources: [dragonflies/status]
    verbs: [get, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dragonfly-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dragonfly-operator
subjects:
  - kind: ServiceAccount
    name: dragonfly-operator
    namespace: database
