ungrouped:
  hosts:
    # edge:
    server:
    hdb:

# kubernetes:
#   hosts:
#     node[01:03].kube.rostvik.site:
#     node04.kube.rostvik.site:
#       set_hostname: node04.kube.rostvik.site
#     controlplane.kube.rostvik.site:
#       is_controlplane: True

pihole:
  hosts:
    pihole1:
      set_hostname: pihole1.{{ secret_local_domain }}
    pihole2:
      set_hostname: pihole2.{{ secret_local_domain }}
