all:
  children:
    raspberry:
      hosts:
        pihole[1:2]:
        node[01:03].kube.rostvik.site:
    kubernetes:
      hosts:
        node[01:03].kube.rostvik.site:
        controlplane.kube.rostvik.site:
    pihole:
      hosts:
        pihole1:
          set_hostname: pihole1.{{ secret_local_domain }}
        pihole2:
          set_hostname: pihole2.{{ secret_local_domain }}
