all:
  hosts:
    pihole1:
      set_hostname: pihole1.{{ secret_local_domain }}
    pihole2:
      set_hostname: pihole2.{{ secret_local_domain }}
  children:
    raspberry:
      hosts:
        pihole[1:2]:
    pihole:
      hosts:
        pihole[1:2]:
