all:
  children:
    nfs_media:
      hosts:
        node04.kube.rostvik.site:
          set_hostname: node04.kube.rostvik.site
    kubernetes:
      hosts:
        node[01:04].kube.rostvik.site:
        controlplane.kube.rostvik.site:
          is_controlplane: True
    pihole:
      hosts:
        pihole1:
          set_hostname: pihole1.{{ secret_local_domain }}
    pihole2:
      set_hostname: pihole2.{{ secret_local_domain }}
    server:
      hosts:
        10.0.0.199:
          set_hostname: server.{{ secret_local_domain }}
    cloud:
      hosts:
        hbd:
    docker:
      hosts:
        10.0.0.199:
        hbd:
