- name: Fetch metadata
  hosts: all
  tags:
    - always
  tasks:
    - name: Get dpkg arch
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
      ansible.builtin.command: dpkg --print-architecture
      register: _apt_arch
      changed_when: false

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Stop unattended-upgr
      become: true
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_facts.services["unattended-upgrades.service"] is defined
      register: unattended_upgr
      ansible.builtin.service:
        name: unattended-upgrades
        state: stopped

- name: Set up ident
  hosts: all
  tags: [never, init]

  pre_tasks:
    - name: Provision users
      ansible.builtin.include_role:
        name: rox_users
      with_items: "{{ users }}"
      loop_control:
        loop_var: user

    - name: Install Homebrew
      ansible.builtin.include_role:
        name: homebrew
      when: homebrew

    - name: Change hostname
      become: true
      when: set_hostname is defined
      ansible.builtin.hostname:
        name: "{{ set_hostname }}"
      notify:
        - Change hostname in hosts

    - name: Update apt cache
      become: true
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

  roles:
    - role: geerlingguy.ntp
      become: true
    - role: bodsch.snapd
      become: true
      when: ansible_distribution == 'Ubuntu'
    - role: geerlingguy.security
      become: true
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
    - role: prometheus.prometheus.node_exporter
      become: true
      when: prom_node_exporter
  tasks:
    - name: Install packages
      become: true
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
      ansible.builtin.apt:
        name: "{{ package_list }}"
        state: present

  handlers:
    - name: Change hostname in hosts
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ^127\.0\.0\.1 localhost
        line: 127.0.0.1 {{ item }}
        owner: root
        group: root
        mode: 0644
      with_items:
        - localhost
        - "{{ set_hostname }}"
      notify:
        - Reboot the server

    - name: Reboot the server
      become: true
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible due to hostname change
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 2
        post_reboot_delay: 30
        test_command: uptime

- name: Setup Netplan
  hosts:
    - edge
    - server
  tags:
    - netplan
    - init
  roles:
    - role: netplan

- name: Install docker
  hosts:
    - edge
    - hbd
    - server
  tags:
    - docker
    - init
  roles:
    - role: geerlingguy.docker
      become: true
      when: ansible_distribution == 'Ubuntu'

- name: Board specific setup
  hosts: all
  tags:
    - init
    - update
  tasks:
    - name: Include ZimaBoard role
      ansible.builtin.include_role:
        name: zimaboard
      when: ansible_facts.board_name is match("ZimaBoard")
    - name: Include raspberry role
      ansible.builtin.include_role:
        name: raspberry
      when: ansible_facts.kernel.endswith("-raspi")

- name: Provision Edge server
  hosts: edge
  tags:
    - edge
    - update
    - init
  roles:
    - role: prometheus.prometheus.prometheus
      vars:
        prometheus_scrape_configs:
          - job_name: prometheus
            metrics_path: "{{ prometheus_metrics_path }}"
            static_configs:
              - targets:
                  - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
          - job_name: node
            file_sd_configs:
              - files:
                  - "{{ prometheus_config_dir }}/file_sd/node.yml"
          - job_name: nodes
            metrics_path: /metrics
            static_configs:
              - targets: # "{{ ((ansible_play_hosts_all | map('extract', hostvars, ['ansible_default_ipv4', 'address'])) | product([':9100'])) | map('join') }}"
                  - localhost:9100
                  - 10.0.0.15:9100

- name: Provision PiHole
  hosts: pihole
  tags:
    - pihole
    - update
    - init
  roles:
    - role: pihole
    - role: pihole_updatelist
    - role: dnsmasq_server
    - role: unbound

- name: Install ZFS
  hosts: server
  tags: [never, init]
  roles:
    - role: zfs

- name: Install Kubernetes
  any_errors_fatal: true
  hosts: kubernetes
  tags:
    - init
    - kubernetes
    - never
  tasks:
    - name: Include Containerd role
      ansible.builtin.include_role:
        name: geerlingguy.containerd
        apply:
          become: true
    - name: Include Kubernetes role
      ansible.builtin.include_role:
        name: kubernetes

- name: Mount unraid media
  hosts:
    - server
    - node04
  tags:
    - init
    - update

  tasks:
    - name: Get dependencies for NFS
      become: true
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
      ansible.builtin.apt:
        name: nfs-common

    - name: Mount unraid media
      become: true
      ansible.posix.mount:
        src: 10.0.0.30:/mnt/user/data/media/
        path: /mnt/user/data/media/
        opts: ro
        state: "{{ 'present' if lookup('file', '/mnt/user/data/media/.test', errors='ignore') else 'mounted' }}"
        fstype: nfs

- name: Update host
  hosts: all
  tags:
    - init
    - update

  tasks:
    # https://www.cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux/
    - name: Update packages
      become: true
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
      ansible.builtin.apt:
        update_cache: "true"
        force_apt_get: "true"
        cache_valid_time: 3600
        upgrade: "yes"
        autoremove: "true"

    - name: Remove Ubuntu ESM apt spam
      become: true
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.copy:
        content: |
          # Ansible managed
        dest: /etc/apt/apt.conf.d/20apt-esm-hook.conf

    - name: Remove motd
      become: true
      ansible.builtin.file:
        path: /etc/motd
        state: absent

    - name: Remove update-motd
      become: true
      ansible.builtin.file:
        path: /etc/update-motd.d/{{ item }}
        state: absent
      loop:
        - 00-header
        - 10-help-text
        - 10-uname
        - 50-motd-news
        - 80-livepatch
        - 88-esm-announce
        - 91-contract-ua-esm-status
        - 91-release-upgrade
        - 92-unattended-upgrades
        - 98-reboot-required
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Place MoTD
      become: true
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
      ansible.builtin.copy:
        content: |
          #!/bin/sh
          # Ansible managed

          neofetch
        mode: 0755
        dest: /etc/update-motd.d/01-neofetch

    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      register: reboot_required_file
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no

    - name: Reboot the server
      become: true
      throttle: 1
      when: reboot_required_file.stat.exists and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible due to kernel updates
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime

- name: Cleanup
  hosts: all
  tags:
    - always
  tasks:
    - name: Start unattended-upgr
      become: true
      when: unattended_upgr.changed
      ansible.builtin.service:
        name: unattended-upgrades
        state: started
