---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/flux/roxedus.net
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
