- name: Create Grafana directories
  become: true
  ansible.builtin.file:
    path: "{{ edge_docker_appdata_path }}/grafana/{{ item }}"
    state: directory
    mode: "{{ edge_docker_mode }}"
    owner: "{{ edge_docker_user }}"
    group: "{{ edge_docker_group }}"
  loop:
    - dashboards
    - grafana
    - provisioning/dashboards
    - provisioning/datasources
    - loki
    - loki/config
    - loki/storage
    - promtail

- name: Set up Grafana
  ansible.builtin.include_role:
    name: compose_generator
  vars:
    compose_generator_service: grafana

- name: Grafana provisioning
  ansible.builtin.template:
    src: grafana/{{ item }}
    dest: "{{ edge_docker_appdata_path }}/grafana/{{ item }}"
    mode: "0775" # To prevent unnecessary nag in logs
    owner: "{{ edge_docker_user }}"
    group: "{{ edge_docker_group }}"
  become: true
  loop:
    - provisioning/dashboards/dash.yaml
    - provisioning/datasources/prometheus.yaml
    - provisioning/datasources/loki.yaml
  notify: Restart grafana after config change

- name: Download Grafana dashboards
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ edge_docker_appdata_path }}/grafana/dashboards/{{ item.name }}"
    mode: "0775" # To prevent unnecessary nag in logs
    owner: "{{ edge_docker_user }}"
    group: "{{ docker_group }}"
  loop:
    - url: https://grafana.com/api/dashboards/1860/revisions/33/download
      name: NodeExporter.json
    - url: https://raw.githubusercontent.com/eko/pihole-exporter/v0.4.0/grafana/dashboard.json
      name: PiholeExporter.json
  notify: Restart grafana after config change

- name: Loki provisioning
  ansible.builtin.template:
    src: grafana/{{ item.src }}
    dest: "{{ edge_docker_appdata_path }}/grafana/{{ item.dest }}"
    mode: "0775" # To prevent unnecessary nag in logs
    owner: "{{ edge_docker_user }}"
    group: "{{ edge_docker_group }}"
  become: true
  loop:
    - src: loki/config.yaml
      dest: loki/config/config.yaml
    - src: promtail/config.yaml
      dest: promtail/config.yaml
  notify: Restart loki after config change
