- name: Create intranet network
  community.docker.docker_network:
    name: "{{ compose_globals.networks.default.name }}"
    driver_options:
      com.docker.network.bridge.name: "{{ compose_globals.networks.default.name }}"
    labels: "{{ compose_globals.networks.default.labels }}"

- name: Create appdata directory
  become: true
  ansible.builtin.file:
    path: "{{ docker_appdata_path }}"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user }}"
    group: "{{ docker_group }}"

- name: Set up Traefik
  ansible.builtin.include_tasks: traefik.yml

- name: Set up Syslog-ng
  ansible.builtin.include_tasks: syslog-ng.yml

- name: Set up Grafana
  ansible.builtin.include_tasks: grafana.yml

- name: Set up healthchecks
  ansible.builtin.include_role:
    name: compose_generator
  vars:
    docker_service: healthchecks

- name: Set up containers
  ansible.builtin.include_role:
    name: compose_generator
  vars:
    docker_service: "{{ item }}"
  loop:
    - vdi
