- name: Create Syslog-ng directory
  become: true
  ansible.builtin.file:
    path: "{{ edge_docker_appdata_path }}/syslog-ng/{{ item }}"
    state: directory
    mode: "{{ edge_docker_dir_mode }}"
    owner: "{{ edge_docker_user }}"
    group: "{{ edge_docker_group }}"
  loop:
    - log
    - config

- name: Set up Syslog-ng
  ansible.builtin.include_role:
    name: compose_generator
  vars:
    compose_generator_service: syslog-ng

- name: Syslog-ng conf
  ansible.builtin.template:
    src: syslog-ng/syslog-ng.conf.j2
    dest: "{{ edge_docker_appdata_path }}/syslog-ng/config/syslog-ng.conf"
    mode: "{{ edge_docker_file_mode }}"
    owner: "{{ edge_docker_user }}"
    group: "{{ edge_docker_group }}"
  become: true
  notify: Restart syslog-ng after config change
