netplan_custom: False

netplan_config_file: /etc/netplan/00-ansible-config.yaml

netplan_addresses: []
netplan_dhcp: False
netplan_dns: []
netplan_gateway4: ""
netplan_interface: "{{  ansible_default_ipv4.alias }}"
netplan_ipv4: ""
netplan_search: []
