---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app satisfactory
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/main/main/default/satisfactory/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: satisfactory-volsync
  namespace: flux-system
spec:
  targetNamespace: default
  path: ./kubernetes/main/kustomize/volsync
  dependsOn:
    - name: satisfactory
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      APP: satisfactory
      VOLSYNC_CACHE_CAPACITY: 25Gi
      CLAIM: satisfactory-data
      VOLSYNC_UID: &UID "1000"
      VOLSYNC_GID: *UID
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
