- name: Restart cloudflared after config change
  register: edge_restart_cloudflared
  changed_when: edge_restart_cloudflared.rc == 0
  ansible.builtin.command:
    cmd: docker restart cloudflared

- name: Restart traefik after config change
  register: edge_restart_traefik
  changed_when: edge_restart_traefik.rc == 0
  ansible.builtin.command:
    cmd: docker restart traefik

- name: Restart syslog-ng after config change
  register: edge_restart_syslog
  changed_when: edge_restart_syslog.rc == 0
  ansible.builtin.command:
    cmd: docker restart syslog-ng

- name: Restart grafana after config change
  register: edge_restart_grafana
  changed_when: edge_restart_grafana.rc == 0
  ansible.builtin.command:
    cmd: docker restart grafana

- name: Restart loki after config change
  register: edge_restart_loki
  changed_when: edge_restart_loki.rc == 0
  ansible.builtin.shell: # noqa command-instead-of-shell
    cmd: docker restart loki && docker restart promtail
