---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-ceph-dashboard
spec:
  target:
    name: rook-ceph-dashboard-password
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: ec889e06-2324-4cf7-8c23-dcfe6578b8db
        property: password
