---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atm10
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: atm10-secret
    template:
      engineVersion: v2
      data:
        CF_API_KEY: "{{ .COURSE_FORGE_API_KEY }}"
        RESTIC_REPOSITORY: "{{ .RESTIC_REST }}/atm10"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        RESTIC_REST_USERNAME: "{{ .RESTIC_REST_USERNAME }}"
        RESTIC_REST_PASSWORD: "{{ .RESTIC_REST_PASSWORD }}"
  dataFrom:
    - extract:
        key: 247cfa93-2894-44bb-918b-892c044a9ef1 # restic-server
    - extract:
        key: 3e016d07-6eb1-4237-bcfb-6f81128d7568
