---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app satisfactory
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/default/satisfactory/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: satisfactory-volsync
  namespace: flux-system
spec:
  targetNamespace: default
  path: ./kubernetes/kustomize/volsync
  dependsOn:
    - name: satisfactory
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      APP: satisfactory
      VOLSYNC_CACHE_CAPACITY: 50Gi
      CLAIM: satisfactory-data
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
